package changecontrol

import (
	"errors"

	"github.com/CodeZen-Lizhi/zhixu/internal/authoring/domain"
	"github.com/CodeZen-Lizhi/zhixu/internal/foundation"
)

func generatedPublicationEvidence(createdByType string) (string, error) {
	switch createdByType {
	case "USER":
		return publicationEvidence, nil
	case "AGENT":
		return "The content is an immutable Authoring Article Revision generated by an AGENT and awaiting user approval.", nil
	case "SYSTEM":
		return "The content is an immutable Authoring Article Revision created by SYSTEM and awaiting user approval.", nil
	default:
		return "", foundation.NewError(foundation.ErrorInvalidInput, domain.ErrorCodePublicationInvalid, false, errors.New("publication author provenance is invalid"))
	}
}
