#!/usr/bin/env bash

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export ZHIXU_COMPOSE_WORKSPACE_ANALYSIS=1
export ZHIXU_COMPOSE_WORKSPACE_ANALYSIS_WORKER_RESTART=1
export ZHIXU_COMPOSE_RAG_REAL_PROVIDER=0
export ZHIXU_COMPOSE_RAG_REAL_PROVIDER_PREFLIGHT_ONLY=0
export ZHIXU_COMPOSE_RAG_SMOKE_TIMEOUT_SECONDS="${ZHIXU_COMPOSE_RAG_SMOKE_TIMEOUT_SECONDS:-420}"

exec bash "${SCRIPT_DIR}/compose-rag-smoke.sh" "$@"
