receivers:
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:4318

processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_mib: 128

exporters:
  nop: {}
  prometheus:
    endpoint: 127.0.0.1:8889
    enable_open_metrics: true
    without_scope_info: true
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  health_check:
    endpoint: 127.0.0.1:13133

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: warn
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [nop]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
