//go:build integration

package postgres

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	authoringchangecontrol "github.com/CodeZen-Lizhi/zhixu/internal/authoring/adapter/changecontrol"
	authoringapp "github.com/CodeZen-Lizhi/zhixu/internal/authoring/application"
	"github.com/CodeZen-Lizhi/zhixu/internal/authoring/domain"
	changecontrollocalfs "github.com/CodeZen-Lizhi/zhixu/internal/changecontrol/adapter/localfs"
	changecontrolpostgres "github.com/CodeZen-Lizhi/zhixu/internal/changecontrol/adapter/postgres"
	changecontrolapp "github.com/CodeZen-Lizhi/zhixu/internal/changecontrol/application"
	changecontroldomain "github.com/CodeZen-Lizhi/zhixu/internal/changecontrol/domain"
	eventspostgres "github.com/CodeZen-Lizhi/zhixu/internal/events/adapter/postgres"
	eventsapp "github.com/CodeZen-Lizhi/zhixu/internal/events/application"
	eventsdomain "github.com/CodeZen-Lizhi/zhixu/internal/events/domain"
	"github.com/CodeZen-Lizhi/zhixu/internal/foundation"
	platformpostgres "github.com/CodeZen-Lizhi/zhixu/internal/platform/postgres"
	workspacedomain "github.com/CodeZen-Lizhi/zhixu/internal/workspace/domain"
)

func TestGeneratedAuthoringPostgreSQLPublicationRetirementAtomic(t *testing.T) {
	fixture := newGeneratedPublicationFixture(t)
	ctx := t.Context()
	first := fixture.candidate(t, 22000)
	if first.publication.Status != domain.PublicationPending || first.proposal.Status != changecontroldomain.StatusReady ||
		first.publication.TargetMode != domain.ProposalTargetCreateOnly || first.proposal.Revision.Content != first.generated.Request.Content ||
		!strings.Contains(first.proposal.Revision.EvidenceSummary, "generated by an AGENT") || first.proposal.Approval != nil {
		t.Fatalf("generated candidate did not create an exact unapproved Proposal: %+v", first.proposal)
	}
	fixture.assertNoFiles(t)
	next := generatedIntegrationSuccessor(t, first.generated, first.result, 22100, fixture.now.Add(4*time.Second))
	nextReservation := generatedReservationRecord(t, next, 22109, fixture.now.Add(5*time.Second))
	err := fixture.uow.Within(ctx, foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
		_, err := fixture.repository.AppendGeneratedRevisionScoped(ctx, scope, next)
		return err
	})
	if !authoringIntegrationError(err, foundation.ErrorVersionConflict, domain.ErrorCodeGeneratedPublicationBusy) {
		t.Fatalf("new generation ignored the existing review window: %v", err)
	}
	retirement := generatedRetirementRecord(t, first, fixture.now.Add(3*time.Second))
	for _, test := range []struct {
		name   string
		mutate func(*domain.GeneratedPublicationRetirementRequest)
		kind   foundation.ErrorKind
		code   string
	}{
		{"origin", func(value *domain.GeneratedPublicationRetirementRequest) {
			value.OriginID = authoringIntegrationID(22991)
		}, foundation.ErrorVersionConflict, domain.ErrorCodeGeneratedOriginConflict},
		{"projection", func(value *domain.GeneratedPublicationRetirementRequest) {
			value.ProjectionHash = strings.Repeat("f", 64)
		}, foundation.ErrorVersionConflict, domain.ErrorCodeGeneratedOriginConflict},
		{"document version", func(value *domain.GeneratedPublicationRetirementRequest) { value.ExpectedDocumentVersion++ }, foundation.ErrorVersionConflict, domain.ErrorCodeGeneratedOriginConflict},
		{"proposal version", func(value *domain.GeneratedPublicationRetirementRequest) { value.ExpectedProposalVersion++ }, foundation.ErrorVersionConflict, domain.ErrorCodeGeneratedPublicationBusy},
		{"publication", func(value *domain.GeneratedPublicationRetirementRequest) {
			value.PublicationID = authoringIntegrationID(22992)
		}, foundation.ErrorNotFound, authoringapp.ErrorCodeNotFound},
		{"workspace", func(value *domain.GeneratedPublicationRetirementRequest) {
			value.WorkspaceID = fixture.otherWorkspaceID
		}, foundation.ErrorNotFound, authoringapp.ErrorCodeNotFound},
	} {
		t.Run(test.name, func(t *testing.T) {
			changed := retirement
			test.mutate(&changed.Request)
			changed.RequestHash, _ = domain.ComputeGeneratedPublicationRetirementRequestHash(changed.Request)
			err := fixture.uow.Within(ctx, foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
				_, err := fixture.repository.RetireGeneratedPublicationScoped(ctx, scope, changed, fixture.retirer)
				return err
			})
			if !authoringIntegrationError(err, test.kind, test.code) {
				t.Fatalf("forged retirement was accepted: %v", err)
			}
		})
	}
	// A participant claiming success without retiring the actual Proposal cannot
	// close the Authoring binding: its existing database terminal guard rejects it.
	err = fixture.uow.Within(ctx, foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
		_, err := fixture.repository.RetireGeneratedPublicationScoped(ctx, scope, retirement,
			generatedRetirerFunc(func(context.Context, foundation.TransactionScope, authoringapp.GeneratedProposalRetirement) error {
				return nil
			}))
		return err
	})
	if platformpostgres.SQLState(err) != "23514" {
		t.Fatalf("closed binding accepted a fake terminal Proposal: %v", err)
	}
	rollback := errors.New("new semantic candidate rejected")
	var nextResult authoringapp.GeneratedRevisionResult
	var retired authoringapp.RetireGeneratedPublicationResult
	appendCandidate := func(ctx context.Context, scope foundation.TransactionScope) error {
		var err error
		retired, err = fixture.repository.RetireGeneratedPublicationScoped(ctx, scope, retirement, fixture.retirer)
		if err != nil {
			return err
		}
		nextResult, err = fixture.repository.AppendGeneratedRevisionScoped(ctx, scope, next)
		if err != nil {
			return err
		}
		_, err = fixture.repository.ReservePublicationScoped(ctx, scope, nextReservation)
		return err
	}
	err = fixture.uow.Within(ctx, foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
		if err := appendCandidate(ctx, scope); err != nil {
			return err
		}
		return rollback
	})
	if !errors.Is(err, rollback) {
		t.Fatalf("candidate rollback cause changed: %v", err)
	}
	fixture.assertCandidateState(t, first, changecontroldomain.StatusReady, domain.PublicationPending, 1)
	assertGeneratedCount(t, fixture.database, "core.article_revision", "id", string(next.Request.ArticleRevisionID), 0)
	assertGeneratedCount(t, fixture.database, "authoring.generated_publication_retirement", "publication_id", string(first.publication.ID), 0)
	assertGeneratedCount(t, fixture.database, "authoring.document_publication_reservation", "id", string(nextReservation.ReservationID), 0)

	lostResponse := errors.New("retirement commit response lost")
	if err := (authoringCommitResponseLossUnitOfWork{delegate: fixture.uow, cause: lostResponse}).Within(ctx, foundation.TransactionOptions{}, appendCandidate); !errors.Is(err, lostResponse) {
		t.Fatalf("retirement response loss was hidden: %v", err)
	}
	if retired.Replayed || retired.Publication.Status != domain.PublicationClosed || nextResult.Document.Version != first.result.Document.Version+1 {
		t.Fatalf("retirement did not atomically append the new candidate: retired=%+v next=%+v", retired, nextResult)
	}
	fixture.assertCandidateState(t, first, changecontroldomain.StatusNeedsRevision, domain.PublicationClosed, 2)
	assertGeneratedCount(t, fixture.database, "authoring.generated_publication_retirement", "publication_id", string(first.publication.ID), 1)
	if err := fixture.uow.Within(ctx, foundation.TransactionOptions{}, appendCandidate); err != nil || !retired.Replayed || !nextResult.Replayed {
		t.Fatalf("committed candidate did not exactly recover after response loss: %v", err)
	}
	var replay authoringapp.RetireGeneratedPublicationResult
	err = fixture.uow.Within(ctx, foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
		var err error
		replay, err = fixture.repository.RetireGeneratedPublicationScoped(ctx, scope, retirement,
			generatedRetirerFunc(func(context.Context, foundation.TransactionScope, authoringapp.GeneratedProposalRetirement) error {
				return errors.New("retirement replay invoked Change Control again")
			}))
		return err
	})
	if err != nil || !replay.Replayed || replay.Publication != retired.Publication {
		t.Fatalf("retirement replay changed after the document advanced: %+v error=%v", replay, err)
	}
	if err := fixture.database.Exec(`UPDATE authoring.generated_publication_retirement SET expected_document_version=expected_document_version+1 WHERE publication_id=?`, string(first.publication.ID)).Error; platformpostgres.SQLState(err) != "55000" {
		t.Fatalf("retirement receipt was mutable: %v", err)
	}
	second := generatedPublicationCandidate{generated: next, result: nextResult}
	second.publication = fixture.publish(t, next, fixture.now.Add(6*time.Second))
	second.proposal, err = fixture.proposals.GetProposal(ctx, second.publication.ProposalID)
	if err != nil || second.proposal.Status != changecontroldomain.StatusReady || second.proposal.ID == first.proposal.ID ||
		second.proposal.Revision.Content != next.Request.Content || second.proposal.Approval != nil {
		t.Fatalf("new candidate did not get its own exact Proposal: %+v error=%v", second.proposal, err)
	}
	assertGeneratedCount(t, fixture.database, "core.article_revision", "document_id", string(next.Request.DocumentID), 2)
	assertGeneratedCount(t, fixture.database, "change_control.approval", "proposal_id", string(first.proposal.ID), 0)
	fixture.assertNoFiles(t)
	approval := generatedApproval(second, 22110, fixture.now.Add(7*time.Second))
	if _, err := fixture.proposals.Approve(ctx, approval); err != nil {
		t.Fatal(err)
	}
	second.proposal.Version++
	approvedRetirement := generatedRetirementRecord(t, second, fixture.now.Add(8*time.Second))
	err = fixture.uow.Within(ctx, foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
		_, err := fixture.repository.RetireGeneratedPublicationScoped(ctx, scope, approvedRetirement, fixture.retirer)
		return err
	})
	if !authoringIntegrationError(err, foundation.ErrorVersionConflict, domain.ErrorCodeGeneratedPublicationBusy) {
		t.Fatalf("retirement invalidated an actual approval: %v", err)
	}
	fixture.assertCandidateState(t, second, changecontroldomain.StatusApproved, domain.PublicationPending, 2)
	assertGeneratedCount(t, fixture.database, "change_control.approval", "proposal_id", string(second.proposal.ID), 1)
	assertGeneratedCount(t, fixture.database, "authoring.generated_publication_retirement", "publication_id", string(second.publication.ID), 0)
	fixture.assertNoFiles(t)
}

func TestGeneratedAuthoringPostgreSQLRetirementWinsApprovalRace(t *testing.T) {
	fixture := newGeneratedPublicationFixture(t)
	first := fixture.candidate(t, 23000)
	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()
	retirement := generatedRetirementRecord(t, first, fixture.now.Add(3*time.Second))
	approvalDone := make(chan error, 1)
	started := false
	err := fixture.uow.Within(ctx, foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
		if _, err := fixture.repository.RetireGeneratedPublicationScoped(ctx, scope, retirement, fixture.retirer); err != nil {
			return err
		}
		started = true
		go func() {
			_, err := fixture.proposals.Approve(ctx, generatedApproval(first, 23010, fixture.now.Add(4*time.Second)))
			approvalDone <- err
		}()
		return waitGeneratedProposalLock(ctx, fixture.platform, "%change_control.proposal AS proposal%")
	})
	if !started {
		t.Fatalf("retirement did not acquire its candidate locks: %v", err)
	}
	var approvalErr error
	select {
	case approvalErr = <-approvalDone:
	case <-ctx.Done():
		t.Fatalf("approval did not exit after retirement: %v", ctx.Err())
	}
	if err != nil || !authoringIntegrationError(approvalErr, foundation.ErrorVersionConflict, "PROPOSAL_NOT_READY_FOR_REVIEW") {
		t.Fatalf("retirement/approval lock ordering failed: retire=%v approve=%v", err, approvalErr)
	}
	fixture.assertCandidateState(t, first, changecontroldomain.StatusNeedsRevision, domain.PublicationClosed, 2)
	assertGeneratedCount(t, fixture.database, "change_control.approval", "proposal_id", string(first.proposal.ID), 0)
}

func TestGeneratedAuthoringPostgreSQLApprovalWinsRetirementRace(t *testing.T) {
	fixture := newGeneratedPublicationFixture(t)
	first := fixture.candidate(t, 24000)
	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()
	events, err := eventspostgres.NewGORMStore(fixture.platform)
	if err != nil {
		t.Fatal(err)
	}
	gate := generatedApprovalEventGate{delegate: events, entered: make(chan struct{}), release: make(chan struct{})}
	proposals, err := changecontrolpostgres.NewGORMRepository(fixture.platform, gate)
	if err != nil {
		t.Fatal(err)
	}
	approvalDone := make(chan error, 1)
	go func() {
		_, err := proposals.Approve(ctx, generatedApproval(first, 24010, fixture.now.Add(3*time.Second)))
		approvalDone <- err
	}()
	select {
	case <-gate.entered:
	case err := <-approvalDone:
		t.Fatalf("approval did not reach the precommit event barrier: %v", err)
	case <-ctx.Done():
		t.Fatal(ctx.Err())
	}
	retirement := generatedRetirementRecord(t, first, fixture.now.Add(4*time.Second))
	retirementDone := make(chan error, 1)
	go func() {
		retirementDone <- fixture.uow.Within(ctx, foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
			_, err := fixture.repository.RetireGeneratedPublicationScoped(ctx, scope, retirement, fixture.retirer)
			return err
		})
	}()
	lockErr := waitGeneratedProposalLock(ctx, fixture.platform, "%FOR UPDATE OF p,r%")
	close(gate.release)
	var approvalErr, retirementErr error
	select {
	case approvalErr = <-approvalDone:
	case <-ctx.Done():
		t.Fatal(ctx.Err())
	}
	select {
	case retirementErr = <-retirementDone:
	case <-ctx.Done():
		t.Fatal(ctx.Err())
	}
	if lockErr != nil || approvalErr != nil || !authoringIntegrationError(retirementErr, foundation.ErrorVersionConflict, domain.ErrorCodeGeneratedPublicationBusy) {
		t.Fatalf("approval/retirement lock ordering failed: wait=%v approve=%v retire=%v", lockErr, approvalErr, retirementErr)
	}
	fixture.assertCandidateState(t, first, changecontroldomain.StatusApproved, domain.PublicationPending, 2)
	assertGeneratedCount(t, fixture.database, "change_control.approval", "proposal_id", string(first.proposal.ID), 1)
	assertGeneratedCount(t, fixture.database, "authoring.generated_publication_retirement", "publication_id", string(first.publication.ID), 0)
}

func TestGeneratedAuthoringPostgreSQLPublicationMissingParent(t *testing.T) {
	fixture := newGeneratedPublicationFixture(t)
	record := generatedIntegrationRecord(t, fixture.workspaceID, 25000, fixture.now)
	record.Request.TargetPath = "missing-parent/note.md"
	var err error
	record.RequestHash, err = domain.ComputeGeneratedRevisionRequestHash(record.Request)
	if err != nil {
		t.Fatal(err)
	}
	fixture.append(t, record)
	reservation := generatedReservationRecord(t, record, 25009, fixture.now.Add(time.Second))
	if err := fixture.uow.Within(t.Context(), foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
		_, err := fixture.repository.ReservePublicationScoped(ctx, scope, reservation)
		return err
	}); err != nil {
		t.Fatal(err)
	}
	service := fixture.service(t, fixture.now.Add(2*time.Second))
	for range 2 {
		_, err := service.PublishArticleRevision(t.Context(), generatedPublishCommand(record))
		var classified *foundation.Error
		if !errors.As(err, &classified) || classified.Code != "WRITEBACK_TARGET_PARENT_NOT_FOUND" {
			t.Fatalf("missing parent did not fail deterministically: %v", err)
		}
	}
	var stored gormPublicationReservationRecord
	if err := fixture.database.Where("id=?", string(reservation.ReservationID)).Take(&stored).Error; err != nil ||
		stored.Status != string(authoringapp.PublicationReservationAbandoned) || stored.ErrorCode != "WRITEBACK_TARGET_PARENT_NOT_FOUND" {
		t.Fatalf("missing parent reservation was not visibly abandoned: %+v error=%v", stored, err)
	}
	assertGeneratedCount(t, fixture.database, "change_control.proposal", "workspace_id", string(fixture.workspaceID), 0)
	assertGeneratedCount(t, fixture.database, "authoring.document_publication_binding", "document_id", string(record.Request.DocumentID), 0)
	fixture.assertNoFiles(t)
}

func TestGeneratedAuthoringPostgreSQLPublishedBaselineAndHistoricalReplay(t *testing.T) {
	fixture := newGeneratedPublicationFixture(t)
	ctx := t.Context()
	if err := fixture.platform.DB().QueryRow(ctx, `SELECT CURRENT_TIMESTAMP - INTERVAL '1 minute'`).Scan(&fixture.now); err != nil {
		t.Fatal(err)
	}
	first := fixture.candidate(t, 26000)
	reservation, found, err := gormLoadReservation(ctx, fixture.database, fixture.workspaceID, first.publication.ReservationID, false)
	if err != nil || !found {
		t.Fatalf("candidate reservation was not persisted: %v", err)
	}
	// Existing owner fixture writes the full Approval/Authorization/execution/
	// proposal_commit chain. Git and filesystem execution remain composition tests.
	gitCommit := seedAuthoringProposalCommit(t, ctx, fixture.platform, first.proposal, reservation,
		first.generated.Request.Content, 26100, fixture.now.Add(3*time.Second))
	advanced, err := fixture.repository.ReconcilePublications(ctx, authoringapp.ReconcileQuery{
		WorkspaceID: fixture.workspaceID, DocumentID: first.result.Document.ID, Limit: 1, Now: fixture.now.Add(4 * time.Second),
	})
	if err != nil || advanced != 1 {
		t.Fatalf("generated publication did not finalize from its exact commit: advanced=%d error=%v", advanced, err)
	}
	detail, err := fixture.repository.GetDocumentDetail(ctx, fixture.workspaceID, first.result.Document.ID)
	if err != nil || detail.Document.Lifecycle != domain.DocumentPublished || detail.Document.CurrentPublishedRevisionID != first.result.Revision.ID ||
		detail.CurrentRevision == nil || detail.CurrentRevision.Status != domain.RevisionPublished || detail.CurrentRevision.GitCommit != gitCommit ||
		detail.CurrentRevision.CreatedByType != "AGENT" || detail.CurrentRevision.SourceVersionID != "" {
		t.Fatalf("generated publication lost its identity or owner pointer: %+v error=%v", detail, err)
	}
	replay := fixture.append(t, first.generated)
	if !replay.Replayed || replay.Document != first.result.Document || replay.Revision != first.result.Revision {
		t.Fatalf("publishing changed the original generation receipt: %+v", replay)
	}
	next := generatedIntegrationSuccessor(t, first.generated,
		authoringapp.GeneratedRevisionResult{Document: detail.Document, Revision: *detail.CurrentRevision}, 26200, fixture.now.Add(5*time.Second))
	nextReservation := generatedReservationRecord(t, next, 26209, fixture.now.Add(6*time.Second))
	var appended authoringapp.GeneratedRevisionResult
	var prepared authoringapp.PublicationPreparation
	err = fixture.uow.Within(ctx, foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
		var err error
		appended, err = fixture.repository.AppendGeneratedRevisionScoped(ctx, scope, next)
		if err != nil {
			return err
		}
		prepared, err = fixture.repository.ReservePublicationScoped(ctx, scope, nextReservation)
		return err
	})
	if err != nil || appended.Document.CurrentPublishedRevisionID != first.result.Revision.ID || appended.Document.Lifecycle != domain.DocumentPublished ||
		appended.Document.Version != detail.Document.Version+1 || appended.Revision.Status != domain.RevisionDraft ||
		prepared.Reservation.TargetMode != domain.ProposalTargetReplace || prepared.Reservation.BaseVersion != first.result.Revision.ContentHash {
		t.Fatalf("next candidate changed the published baseline: appended=%+v prepared=%+v error=%v", appended, prepared, err)
	}
	// Represent the already-written file for the real read-only Proposal reader.
	path := filepath.Join(fixture.rootPath, first.generated.Request.TargetPath)
	if err := os.WriteFile(path, []byte(first.generated.Request.Content), 0o600); err != nil {
		t.Fatal(err)
	}
	publication := fixture.publish(t, next, fixture.now.Add(7*time.Second))
	if publication.TargetMode != domain.ProposalTargetReplace || publication.Status != domain.PublicationPending {
		t.Fatalf("successor did not create a governed replacement: %+v", publication)
	}
	content, err := os.ReadFile(path)
	if err != nil || string(content) != first.generated.Request.Content {
		t.Fatalf("unapproved replacement changed the current file: %v", err)
	}
}

type generatedPublicationFixture struct {
	generatedAuthoringFixture
	proposals *changecontrolpostgres.GORMRepository
	retirer   authoringapp.GeneratedProposalRetirer
	reader    *changecontrollocalfs.Reader
	rootPath  string
}

type generatedPublicationCandidate struct {
	generated   authoringapp.GeneratedRevisionRecord
	result      authoringapp.GeneratedRevisionResult
	publication domain.PublicationBinding
	proposal    changecontroldomain.Proposal
}

func newGeneratedPublicationFixture(t *testing.T) generatedPublicationFixture {
	t.Helper()
	base := newGeneratedAuthoringFixture(t)
	proposals, err := changecontrolpostgres.NewGORMRepository(base.platform)
	if err != nil {
		t.Fatal(err)
	}
	retirer, err := authoringchangecontrol.NewGeneratedPublicationRetirer(proposals)
	if err != nil {
		t.Fatal(err)
	}
	rootPath := t.TempDir()
	reader, err := changecontrollocalfs.NewReader(generatedWorkspaceReader{workspacedomain.Workspace{ID: base.workspaceID, RootPath: rootPath}})
	if err != nil {
		t.Fatal(err)
	}
	return generatedPublicationFixture{generatedAuthoringFixture: base, proposals: proposals, retirer: retirer, reader: reader, rootPath: rootPath}
}

func (fixture generatedPublicationFixture) service(t *testing.T, at time.Time) *authoringapp.Service {
	t.Helper()
	proposals, err := changecontrolapp.NewService(fixture.proposals, foundation.NewUUIDGenerator(nil), foundation.FixedClock{Value: at}, fixture.reader, authoringIntegrationGitInspector{})
	if err != nil {
		t.Fatal(err)
	}
	creator, err := authoringchangecontrol.NewProposalCreator(proposals, fixture.reader)
	if err != nil {
		t.Fatal(err)
	}
	service, err := authoringapp.NewService(authoringapp.Dependencies{Repository: fixture.repository, IDs: foundation.NewUUIDGenerator(nil), Clock: foundation.FixedClock{Value: at}, Proposals: creator})
	if err != nil {
		t.Fatal(err)
	}
	return service
}

func (fixture generatedPublicationFixture) candidate(t *testing.T, base int) generatedPublicationCandidate {
	t.Helper()
	result := generatedPublicationCandidate{generated: generatedIntegrationRecord(t, fixture.workspaceID, base, fixture.now)}
	reservation := generatedReservationRecord(t, result.generated, base+9, fixture.now.Add(time.Second))
	if err := fixture.uow.Within(t.Context(), foundation.TransactionOptions{}, func(ctx context.Context, scope foundation.TransactionScope) error {
		var err error
		result.result, err = fixture.repository.AppendGeneratedRevisionScoped(ctx, scope, result.generated)
		if err != nil {
			return err
		}
		_, err = fixture.repository.ReservePublicationScoped(ctx, scope, reservation)
		return err
	}); err != nil {
		t.Fatal(err)
	}
	result.publication = fixture.publish(t, result.generated, fixture.now.Add(2*time.Second))
	var err error
	result.proposal, err = fixture.proposals.GetProposal(t.Context(), result.publication.ProposalID)
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func (fixture generatedPublicationFixture) publish(t *testing.T, record authoringapp.GeneratedRevisionRecord, at time.Time) domain.PublicationBinding {
	t.Helper()
	result, err := fixture.service(t, at).PublishArticleRevision(t.Context(), generatedPublishCommand(record))
	if err != nil {
		t.Fatal(err)
	}
	return result.Publication
}

func generatedPublishCommand(record authoringapp.GeneratedRevisionRecord) authoringapp.PublishCommand {
	return authoringapp.PublishCommand{WorkspaceID: record.Request.WorkspaceID, DocumentID: record.Request.DocumentID, RevisionID: record.Request.ArticleRevisionID, IdempotencyKey: "publish-" + record.IdempotencyKey}
}

func generatedRetirementRecord(t *testing.T, candidate generatedPublicationCandidate, at time.Time) authoringapp.RetireGeneratedPublicationRecord {
	t.Helper()
	generated := candidate.generated.Request
	request := domain.GeneratedPublicationRetirementRequest{WorkspaceID: generated.WorkspaceID, DocumentID: generated.DocumentID,
		ArticleRevisionID: generated.ArticleRevisionID, PublicationID: candidate.publication.ID, OriginKind: generated.OriginKind,
		OriginID: generated.OriginID, OriginRevisionID: generated.OriginRevisionID, ProjectionHash: generated.ProjectionHash,
		ExpectedDocumentVersion: candidate.result.Document.Version, ExpectedProposalVersion: candidate.proposal.Version}
	hash, err := domain.ComputeGeneratedPublicationRetirementRequestHash(request)
	if err != nil {
		t.Fatal(err)
	}
	return authoringapp.RetireGeneratedPublicationRecord{Request: request, IdempotencyKey: "retire-" + candidate.generated.IdempotencyKey, RequestHash: hash, RetiredAt: at}
}

func generatedApproval(candidate generatedPublicationCandidate, id int, at time.Time) changecontroldomain.Approval {
	head := strings.Repeat("a", 40)
	return changecontroldomain.Approval{ID: authoringIntegrationID(id), ProposalID: candidate.proposal.ID, RevisionID: candidate.proposal.Revision.ID,
		ChangeHash: candidate.proposal.Revision.ChangeHash, Decision: changecontroldomain.DecisionApproved, ApprovedGitHead: &head, DecidedAt: at}
}

func (fixture generatedPublicationFixture) assertCandidateState(t *testing.T, candidate generatedPublicationCandidate, proposalStatus changecontroldomain.ProposalStatus, publicationStatus domain.PublicationStatus, proposalVersion int64) {
	t.Helper()
	proposal, err := fixture.proposals.GetProposal(t.Context(), candidate.proposal.ID)
	if err != nil || proposal.Status != proposalStatus || proposal.Version != proposalVersion || proposal.Revision.ID != candidate.proposal.Revision.ID || proposal.Revision.Content != candidate.generated.Request.Content {
		t.Fatalf("candidate Proposal state changed incorrectly: %+v error=%v", proposal, err)
	}
	binding, found, err := gormLoadPublicationID(t.Context(), fixture.database, candidate.generated.Request.WorkspaceID, candidate.publication.ID, false)
	if err != nil || !found || binding.Status != publicationStatus || binding.ProposalRevisionID != candidate.proposal.Revision.ID || binding.ArticleRevisionID != candidate.result.Revision.ID {
		t.Fatalf("candidate publication state changed incorrectly: %+v error=%v", binding, err)
	}
}

func (fixture generatedPublicationFixture) assertNoFiles(t *testing.T) {
	t.Helper()
	entries, err := os.ReadDir(fixture.rootPath)
	if err != nil || len(entries) != 0 {
		t.Fatalf("unapplied candidate created Workspace files: entries=%v error=%v", entries, err)
	}
}

func waitGeneratedProposalLock(ctx context.Context, pool *platformpostgres.Pool, queryPattern string) error {
	waitCtx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	ticker := time.NewTicker(10 * time.Millisecond)
	defer ticker.Stop()
	for {
		var waiting bool
		if err := pool.DB().QueryRow(waitCtx, `SELECT EXISTS (
			SELECT 1 FROM pg_stat_activity WHERE datname=current_database() AND pid<>pg_backend_pid()
			AND state='active' AND wait_event_type='Lock' AND query LIKE $1
		)`, queryPattern).Scan(&waiting); err != nil {
			return err
		}
		if waiting {
			return nil
		}
		select {
		case <-ticker.C:
		case <-waitCtx.Done():
			return fmt.Errorf("concurrent candidate command never waited on its Proposal lock: %w", waitCtx.Err())
		}
	}
}

type generatedWorkspaceReader struct{ workspace workspacedomain.Workspace }

func (reader generatedWorkspaceReader) GetWorkspaceByID(_ context.Context, id foundation.ID) (workspacedomain.Workspace, error) {
	if id != reader.workspace.ID {
		return workspacedomain.Workspace{}, errors.New("unexpected Workspace request")
	}
	return reader.workspace, nil
}

type generatedRetirerFunc func(context.Context, foundation.TransactionScope, authoringapp.GeneratedProposalRetirement) error

func (retire generatedRetirerFunc) RetireGeneratedProposalScoped(ctx context.Context, scope foundation.TransactionScope, request authoringapp.GeneratedProposalRetirement) error {
	return retire(ctx, scope, request)
}

// The real event append occurs inside Approve's transaction. The barrier holds
// that transaction immediately before commit so the competing retirement must wait.
type generatedApprovalEventGate struct {
	delegate eventsapp.ScopedAppender
	entered  chan struct{}
	release  chan struct{}
}

func (gate generatedApprovalEventGate) AppendScoped(ctx context.Context, scope foundation.TransactionScope, request eventsdomain.AppendRequest) (eventsdomain.ServerEvent, bool, error) {
	event, replayed, err := gate.delegate.AppendScoped(ctx, scope, request)
	if err != nil {
		return event, replayed, err
	}
	close(gate.entered)
	select {
	case <-gate.release:
		return event, replayed, nil
	case <-ctx.Done():
		return eventsdomain.ServerEvent{}, false, ctx.Err()
	}
}
